version: "3.7"

services:
  webserver:
    build:
      context: "./docker/services/php82"
    container_name: "zephyrus_webserver"
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
      - "1080:1080"
    links:
      - database
    volumes:
      - code:/var/www/html
      #- ./docker/vhosts:/etc/apache2/sites-enabled
      - ./xdebug:/xdebug.d

  database:
    build:
      context: "./docker/services/postgres"
    container_name: 'zephyrus_database'
    restart: 'always'
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/sql
      - ./sql/init-database.sql:/docker-entrypoint-initdb.d/1-database.sql
      - ./sql/init-mocks.sql:/docker-entrypoint-initdb.d/2-data-mocks.sql
    environment:
      POSTGRES_DB: 'zephyrus'
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'dev'

volumes:
  code:

x-mutagen:
  sync:
    defaults:
      mode: 'two-way-resolved'
      ignore:
        vcs: true
        paths:
          - '.idea'
          - 'cache'

    code:
      alpha: '.'
      beta: 'volume://code'
      configurationBeta:
        permissions:
          defaultDirectoryMode: 0777
          defaultFileMode: 0666
          defaultOwner: 'id:33'
          defaultGroup: 'id:33'